# Generated by Django 5.2 on 2026-03-03 06:49

import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_slide_order'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Загрузите изображение для слайда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(help_text='Введите название слайда', max_length=255, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['order'], name='landing_sli_order_f9cdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['created_at'], name='landing_sli_created_6b8fda_idx'),
        ),
    ]
